import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";
import { Grid, Card, Col, Text } from "@nextui-org/react";

const Test: NextPage = () => {
    const hello = trpc.useQuery(["example.hello", { text: "from tRPC" }]);

    return (
        <>
            <Head>
                <title>Test Page</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Grid.Container gap={2} justify="center">
      <Grid xs={4}>
      <Text
                h1
                size={60}
                css={{
                    textGradient: "45deg, $blue600 -20%, $pink600 50%",
                }}
                weight="bold"
            >
                Let's
            </Text>
            <Text
                h1
                size={60}
                css={{
                    textGradient: "45deg, $purple600 -20%, $pink600 100%",
                }}
                weight="bold"
            >
                Make the Web
            </Text>
            <Text
                h1
                size={60}
                css={{
                    textGradient: "45deg, $yellow600 -20%, $red600 100%",
                }}
                weight="bold"
            >
                Prettier
            </Text>
      </Grid>
      <Grid xs={4}>
      <Text
                h1
                size={60}
                css={{
                    textGradient: "45deg, $blue600 -20%, $pink600 50%",
                }}
                weight="bold"
            >
                Let's
            </Text>
            <Text
                h1
                size={60}
                css={{
                    textGradient: "45deg, $purple600 -20%, $pink600 100%",
                }}
                weight="bold"
            >
                Make the Web
            </Text>
            <Text
                h1
                size={60}
                css={{
                    textGradient: "45deg, $yellow600 -20%, $red600 100%",
                }}
                weight="bold"
            >
                Prettier
            </Text>
      </Grid>
      <Grid xs={4}>

      <Card css={{ bg: "$black", w: "15%" }}>
                <Card.Header css={{ position: "absolute", zIndex: 1, top: 5 }}>
                    <Col>
                        <Text size={12} weight="bold" transform="uppercase" color="#ffffffAA">
                            Supercharged
                        </Text>
                        <Text h4 color="white">
                            Creates beauty like a beast
                        </Text>
                    </Col>
                </Card.Header>
                <Card.Image
                    src="https://nextui.org/images/card-example-2.jpeg"
                    width="100%"
                    height={340}
                    objectFit="cover"
                    alt="Card image background"
                />
            </Card>
      </Grid>
    </Grid.Container>
        </>
    );
};

export default Test;
